// Code generated by oto; DO NOT EDIT.

'use strict';
export default class ConferenceService {


	async get(getConferenceRequest) {
		const headers = {
			'Accept': 'application/json',
			'Accept-Encoding': 'gzip',
			'Content-Type': 'application/json',
		}
		getConferenceRequest = getConferenceRequest || {}
		const response = await fetch('https://showrunner-46b2.encoreapi.com/azure/conferences.GetAll', {
			method: 'POST',
			headers: headers,
			body: JSON.stringify(getConferenceRequest)
		})
		return response.json().then((json) => {
			if (json.error) {
				throw new Error(json.error)
			}
			return json
		})
	}


}

